# Generated by Django 4.2 on 2023-05-07 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0004_reporte_timestamp_solicitud_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportes', models.ManyToManyField(to='sistema.reporte')),
                ('solicitudes', models.ManyToManyField(to='sistema.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial_usuarios',
                'verbose_name_plural': 'historiales_usuarios',
            },
        ),
    ]
