# Generated by Django 4.2 on 2023-05-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_historial_reporte_historial_solicitud_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='fecha',
        ),
    ]
