# Generated by Django 4.2 on 2023-05-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
