# Generated by Django 4.2 on 2023-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('equipo', models.CharField(max_length=100)),
                ('diagnostico', models.TextField()),
                ('solucion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('en reparacion', 'en reparacion'), ('de vaja', 'de vaja')], max_length=20)),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
            },
        ),
    ]
